name: rso-app
services:
  # Nginx API Gateway
  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "4000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
    - "host.docker.internal:host-gateway"
    depends_on:
      - auth-db
    networks:
      - microservices-net

  # RabbitMQ Broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ communication port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-net
      
  # PostgreSQL for Auth Service
  auth-db:
    image: postgres:16-alpine
    container_name: auth-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d auth_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-net

  # PostgreSQL for Activity Service
  activity-db:
    image: postgres:16-alpine
    container_name: activity-db
    environment:
      POSTGRES_DB: activity_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    volumes:
      - activity-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d activity_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-net

volumes:
  auth-db-data:
  activity-db-data:

networks:
  microservices-net:
    driver: bridge