replicaCount: 2

image:
  repository: rsoappcr.azurecr.io/activity
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 4002
  grpcPort: 50002

env:
  NODE_ENV: "production"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

readinessProbe:
  httpGet:
    path: /ready
    port: 4002
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 3

livenessProbe:
  httpGet:
    path: /health
    port: 4002
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 3
