apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-clubs
  labels:
    app: clubs
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 4003
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: 50003
      protocol: TCP
  selector:
    app: clubs
    release: {{ .Release.Name }}
