apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq-auth
  labels:
    app: rabbitmq
    release: {{ .Release.Name }}
type: Opaque
data:
  username: {{ .Values.auth.username | b64enc | quote }}
  password: {{ .Values.auth.password | b64enc | quote }}
