apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-rabbitmq
  labels:
    app: rabbitmq
    release: {{ .Release.Name }}
spec:
  serviceName: rabbitmq
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rabbitmq
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: rabbitmq
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.amqpPort }}
              name: amqp
            - containerPort: {{ .Values.service.managementPort }}
              name: management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.auth.username | quote }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.auth.password | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
{{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
{{- end }}
