apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-activity
  labels:
    app: activity
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: activity
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: activity
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: activity
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4002
              protocol: TCP
            - name: grpc
              containerPort: 50002
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: activity-secrets
                  key: database-url
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: activity-secrets
                  key: rabbitmq-url
            - name: WEATHER_FUNCTION_URL
              valueFrom:
                secretKeyRef:
                  name: activity-secrets
                  key: weather-function-url
            - name: AUTH_SERVICE_URL
              value: "http://auth-auth.rso-app.svc.cluster.local:4001"
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
