apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-activity
  labels:
    app: activity
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 4002
      protocol: TCP
  selector:
    app: activity
    release: {{ .Release.Name }}
